spring.application.name=mainwetten

spring.datasource.url=jdbc:postgresql://localhost:5432/mainwetten
spring.datasource.username=mainwetten
spring.datasource.password=mainwetten

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true