spring.application.name=mainwetten

spring.profiles.default=local

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mainwetten}
spring.datasource.username=${DB_USER:mainwetten}
spring.datasource.password=${DB_PASSWORD:mainwetten}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}

spring.flyway.enabled=true

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false